// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function HideApp():Promise<void>;

export function IsAppHidden():Promise<boolean>;

export function ShowApp():Promise<void>;
