// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideApp() {
  return window['go']['main']['App']['HideApp']();
}

export function IsAppHidden() {
  return window['go']['main']['App']['IsAppHidden']();
}

export function ShowApp() {
  return window['go']['main']['App']['ShowApp']();
}
