// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeService(arg1) {
  return window['go']['main']['App']['AuthorizeService'](arg1);
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function HideApp() {
  return window['go']['main']['App']['HideApp']();
}

export function IsAppHidden() {
  return window['go']['main']['App']['IsAppHidden']();
}

export function MountCloud(arg1, arg2, arg3) {
  return window['go']['main']['App']['MountCloud'](arg1, arg2, arg3);
}

export function ShowApp() {
  return window['go']['main']['App']['ShowApp']();
}

export function UnmountCloud(arg1) {
  return window['go']['main']['App']['UnmountCloud'](arg1);
}
