// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeService(arg1) {
  return window['go']['main']['App']['AuthorizeService'](arg1);
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function ConnectToCloud(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToCloud'](arg1, arg2, arg3);
}

export function DisconnectFromCloud(arg1, arg2) {
  return window['go']['main']['App']['DisconnectFromCloud'](arg1, arg2);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function HideApp() {
  return window['go']['main']['App']['HideApp']();
}

export function IsAppHidden() {
  return window['go']['main']['App']['IsAppHidden']();
}

export function MountCloudToLocal(arg1, arg2, arg3) {
  return window['go']['main']['App']['MountCloudToLocal'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ShowApp() {
  return window['go']['main']['App']['ShowApp']();
}

export function UnmountCloud(arg1) {
  return window['go']['main']['App']['UnmountCloud'](arg1);
}
